export const Shadows = {
  ShadowSm: 'shadow-sm',
  ShadowMd: 'shadow-md',
  ShadowLg: 'shadow-lg',
  ShadowXl: 'shadow-xl',
  Modal: 'modal',
  Label: 'label',
  Header: 'header',
  HeaderPopup: 'header-popup',
  FooterPopup: 'footer-popup',
  LeftPanelMd: 'left-panel-md',
  RightPanelMd: 'right-panel-md',
  LeftPanelSm: 'left-panel-sm',
  RightPanelSm: 'right-panel-sm',
} as const;
