export const FontVariant = {
  TextExtraSmall: 'text-extra-small',
  TextSmall: 'text-small',
  TextSmallUp: 'text-small-up',
  TextMedium: 'text-medium',
  TextLarge: 'text-large',
  TextExtraLarge: 'text-extra-large',

  TitleH6: 'title-h6',
  TitleH5: 'title-h5',
  TitleH4: 'title-h4',
  TitleH3: 'title-h3',
  TitleH2: 'title-h2',
  TitleH1: 'title-h1',

  LabelExtraSmall: 'label-extra-small',
  LabelExtraSmallEmphasis: 'label-extra-small-emphasis',
  LabelExtraSmallUp: 'label-extra-small-up',
  LabelSmall: 'label-small',
  LabelSmallEmphasis: 'label-small-emphasis',
  LabelSmallUp: 'label-small-up',
  LabelSmallUpEmphasis: 'label-small-up-emphasis',
  LabelMedium: 'label-medium',
  LabelMediumEmphasis: 'label-medium-emphasis',
  LabelLarge: 'label-large',
  LabelLargeEmphasis: 'label-large-emphasis',
  LabelLargeUp: 'label-large-up',
  LabelExtraLarge: 'label-extra-large',
  LabelXExtraLarge: 'label-x-extra-large',

  ButtonSm: 'btn-sm',
  ButtonSmLink: 'btn-sm-link',
  ButtonSmUp: 'btn-sm-up',
  ButtonSmUpLink: 'btn-sm-up-link',
  ButtonMd: 'btn-md',
  ButtonMdLink: 'btn-md-link',
  ButtonLg: 'btn-lg',
  ButtonLgLink: 'btn-lg-link',
  ButtonLgUp: 'btn-lg-up',
  ButtonLgUpLink: 'btn-lg-up-link',

  LinkSmall: 'link-small',
  LinkSmallEmphasis: 'link-small-emphasis',
  LinkSmallUp: 'link-small-up',
  LinkSmallUpEmphasis: 'link-small-up-emphasis',
  LinkMedium: 'link-medium',
  LinkMediumEmphasis: 'link-medium-emphasis',
  LinkLarge: 'link-large',
  LinkLargeEmphasis: 'link-large-emphasis',
  LinkLargeUp: 'link-large-up',
  LinkLargeUpEmphasis: 'link-large-up-emphasis',

  InputSm: 'input-sm',
  InputSmUp: 'input-sm-up',
  InputMd: 'input-md',
  InputLg: 'input-lg',
} as const;
