export const FontVariant = {
  TextExtraSmall: 'text-extra-small',
  TextSmall: 'text-small',
  TextSmallUp: 'text-small-up',
  TextMedium: 'text-medium',
  TextLarge: 'text-large',
  TextExtraLarge: 'text-extra-large',

  TitleH5: 'title-h5',
  TitleH4: 'title-h4',
  TitleH3: 'title-h3',
  TitleH2: 'title-h2',
  TitleH1: 'title-h1',

  LabelExtraSmall: 'label-extra-small',
  LabelExtraSmallEmphasis: 'label-extra-small-emphasis',
  LabelExtraSmallUp: 'label-extra-small-up',
  LabelSmall: 'label-small',
  LabelSmallEmphasis: 'label-small-emphasis',
  LabelSmallUp: 'label-small-up',
  LabelSmallUpEmphasis: 'label-small-up-emphasis',
  LabelMedium: 'label-medium',
  LabelMediumEmphasis: 'label-medium-emphasis',
  LabelLarge: 'label-large',
  LabelLargeEmphasis: 'label-large-emphasis',
  LabelLargeUp: 'label-large-up',
  LabelExtraLarge: 'label-extra-large',
  LabelXExtraLarge: 'label-x-extra-large',

  ButtonXsLink: 'btn-xs-link',
  ButtonXs: 'btn-xs',
  ButtonXsUp: 'btn-xs-up',
  ButtonSmLink: 'btn-sm-link',
  ButtonSm: 'btn-sm',
  ButtonMdLink: 'btn-md-link',
  ButtonMd: 'btn-md',
  ButtonLg: 'btn-lg',

  InputSm: 'input-sm',
  InputSmUp: 'input-sm-up',
  InputMd: 'input-md',
  InputLg: 'input-lg',
} as const;
